// Function reference shown in Excel Lab, grouped like the practice.
const HELP = [
  { group: 'Math', syntax: 'SUM(number1, [number2], …)', desc: 'Adds numbers and ranges\nText in ranges is ignored' },
  { group: 'Math', syntax: 'AVERAGE(number1, …)', desc: 'Arithmetic mean of the numbers' },
  { group: 'Math', syntax: 'MIN(number1, …)', desc: 'Smallest number' },
  { group: 'Math', syntax: 'MAX(number1, …)', desc: 'Largest number' },
  { group: 'Math', syntax: 'COUNT(value1, …)', desc: 'Counts cells that hold numbers or dates' },
  { group: 'Math', syntax: 'COUNTA(value1, …)', desc: 'Counts cells that are not empty' },
  { group: 'Math', syntax: 'COUNTBLANK(range)', desc: 'Counts empty cells' },
  { group: 'Math', syntax: 'ROUND(number, digits)', desc: 'Rounds half away from zero' },
  { group: 'Math', syntax: 'ROUNDUP(number, digits)', desc: 'Rounds away from zero' },
  { group: 'Math', syntax: 'ROUNDDOWN(number, digits)', desc: 'Rounds toward zero' },
  { group: 'Math', syntax: 'INT(number)', desc: 'Rounds down to a whole number' },
  { group: 'Math', syntax: 'MOD(number, divisor)', desc: 'Remainder after division, with the sign of the divisor' },
  { group: 'Math', syntax: 'ABS(number)', desc: 'Value without its sign' },
  { group: 'Math', syntax: 'MEDIAN(number1, …)', desc: 'Middle value' },
  { group: 'Math', syntax: 'STDEV.S(number1, …)', desc: 'Sample standard deviation' },
  { group: 'Math', syntax: 'LARGE(array, k)', desc: 'The kth largest value' },
  { group: 'Math', syntax: 'SMALL(array, k)', desc: 'The kth smallest value' },
  { group: 'Math', syntax: 'RANK.EQ(number, ref, [order])', desc: 'Rank of a number in a list, largest first unless order is 1' },
  { group: 'Math', syntax: 'PERCENTILE.INC(array, k)', desc: 'The kth percentile, k between 0 and 1' },
  { group: 'Math', syntax: 'SUMPRODUCT(array1, [array2], …)', desc: 'Multiplies arrays item by item and adds the results' },
  { group: 'Conditional', syntax: 'SUMIFS(sum_range, criteria_range1, criteria1, …)', desc: 'Adds values where every condition holds\nCriteria can be text, a number, `">100"`, `"<>x"` or wildcards `*` and `?`' },
  { group: 'Conditional', syntax: 'COUNTIFS(criteria_range1, criteria1, …)', desc: 'Counts rows where every condition holds' },
  { group: 'Conditional', syntax: 'AVERAGEIFS(average_range, criteria_range1, criteria1, …)', desc: 'Average where every condition holds' },
  { group: 'Conditional', syntax: 'MAXIFS(max_range, criteria_range1, criteria1, …)', desc: 'Largest value where every condition holds' },
  { group: 'Conditional', syntax: 'MINIFS(min_range, criteria_range1, criteria1, …)', desc: 'Smallest value where every condition holds' },
  { group: 'Conditional', syntax: 'SUMIF(range, criteria, [sum_range])', desc: 'Single condition version of SUMIFS' },
  { group: 'Conditional', syntax: 'COUNTIF(range, criteria)', desc: 'Single condition version of COUNTIFS' },
  { group: 'Logic', syntax: 'IF(test, value_if_true, [value_if_false])', desc: 'Returns one of two values\nWorks on whole arrays too' },
  { group: 'Logic', syntax: 'IFS(test1, value1, test2, value2, …)', desc: 'First value whose test is true' },
  { group: 'Logic', syntax: 'AND(logical1, …)', desc: 'True when all are true' },
  { group: 'Logic', syntax: 'OR(logical1, …)', desc: 'True when any is true' },
  { group: 'Logic', syntax: 'NOT(logical)', desc: 'Flips true and false' },
  { group: 'Logic', syntax: 'IFERROR(value, value_if_error)', desc: 'Replaces any error' },
  { group: 'Logic', syntax: 'IFNA(value, value_if_na)', desc: 'Replaces only #N/A' },
  { group: 'Logic', syntax: 'SWITCH(expression, value1, result1, …, [default])', desc: 'Matches one value against a list' },
  { group: 'Lookup', syntax: 'XLOOKUP(lookup, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])', desc: 'Modern lookup in any direction\nMatch mode 0 is exact, minus 1 takes the next smaller and 1 the next larger\nSearch mode minus 1 searches from the bottom' },
  { group: 'Lookup', syntax: 'VLOOKUP(lookup, table, column, [approximate])', desc: 'Looks down the first column and returns a value from another column\nUse FALSE for exact match' },
  { group: 'Lookup', syntax: 'HLOOKUP(lookup, table, row, [approximate])', desc: 'Like VLOOKUP but across the first row' },
  { group: 'Lookup', syntax: 'INDEX(array, row, [column])', desc: 'Value at a position' },
  { group: 'Lookup', syntax: 'MATCH(lookup, array, [type])', desc: 'Position of a value\nUse 0 for exact match' },
  { group: 'Lookup', syntax: 'XMATCH(lookup, array, [match_mode], [search_mode])', desc: 'Modern MATCH, exact by default' },
  { group: 'Lookup', syntax: 'CHOOSE(index, value1, value2, …)', desc: 'Picks a value by number' },
  { group: 'Text', syntax: 'LEFT(text, [n])', desc: 'First n characters' },
  { group: 'Text', syntax: 'RIGHT(text, [n])', desc: 'Last n characters' },
  { group: 'Text', syntax: 'MID(text, start, n)', desc: 'n characters from a start position' },
  { group: 'Text', syntax: 'LEN(text)', desc: 'Number of characters' },
  { group: 'Text', syntax: 'UPPER(text) · LOWER(text) · PROPER(text)', desc: 'Change case' },
  { group: 'Text', syntax: 'TRIM(text)', desc: 'Removes extra spaces' },
  { group: 'Text', syntax: 'TEXTJOIN(delimiter, ignore_empty, text1, …)', desc: 'Joins a range with a separator' },
  { group: 'Text', syntax: 'CONCAT(text1, …)', desc: 'Joins text, like the `&` operator' },
  { group: 'Text', syntax: 'SUBSTITUTE(text, old, new, [instance])', desc: 'Replaces text' },
  { group: 'Text', syntax: 'FIND(find, within, [start])', desc: 'Position of text, case sensitive' },
  { group: 'Text', syntax: 'SEARCH(find, within, [start])', desc: 'Position of text, ignores case, allows wildcards' },
  { group: 'Text', syntax: 'TEXT(value, format)', desc: 'Formats a number or date as text, such as `"mmm yyyy"` or `"#,##0.00"`' },
  { group: 'Text', syntax: 'VALUE(text)', desc: 'Turns text into a number' },
  { group: 'Dates', syntax: 'DATE(year, month, day)', desc: 'Builds a date' },
  { group: 'Dates', syntax: 'YEAR(date) · MONTH(date) · DAY(date)', desc: 'Parts of a date' },
  { group: 'Dates', syntax: 'TODAY()', desc: 'Today’s date' },
  { group: 'Dates', syntax: 'EOMONTH(date, months)', desc: 'Last day of the month, months ahead or back' },
  { group: 'Dates', syntax: 'EDATE(date, months)', desc: 'Same day, months ahead or back' },
  { group: 'Dates', syntax: 'WEEKDAY(date, [type])', desc: 'Day of week number, Sunday is 1 by default' },
  { group: 'Dates', syntax: 'WEEKNUM(date, [type])', desc: 'Week of the year' },
  { group: 'Dates', syntax: 'DATEDIF(start, end, unit)', desc: 'Whole days, months or years between dates, unit is `"d"`, `"m"` or `"y"`' },
  { group: 'Dates', syntax: 'NETWORKDAYS(start, end, [holidays])', desc: 'Working days between dates' },
  { group: 'Dynamic arrays', syntax: 'FILTER(array, include, [if_empty])', desc: 'Rows where include is true\nMultiply conditions for AND, add them for OR' },
  { group: 'Dynamic arrays', syntax: 'SORT(array, [index], [order])', desc: 'Sorts by a column, order minus 1 for descending' },
  { group: 'Dynamic arrays', syntax: 'SORTBY(array, by_array, [order], …)', desc: 'Sorts by other ranges' },
  { group: 'Dynamic arrays', syntax: 'UNIQUE(array, [by_col], [exactly_once])', desc: 'Distinct rows' },
  { group: 'Dynamic arrays', syntax: 'SEQUENCE(rows, [columns], [start], [step])', desc: 'A grid of numbers' },
  { group: 'Dynamic arrays', syntax: 'TRANSPOSE(array)', desc: 'Swaps rows and columns' },
  { group: 'Dynamic arrays', syntax: 'TAKE(array, rows, [columns])', desc: 'First rows, or last rows when negative' },
  { group: 'Dynamic arrays', syntax: 'CHOOSECOLS(array, col1, …)', desc: 'Keeps chosen columns' },
  { group: 'Dynamic arrays', syntax: 'LET(name1, value1, …, calculation)', desc: 'Names parts of a formula' },
];

export const FUNCTION_HELP = HELP.map(h => ({ ...h, fn: h.syntax.split('(')[0] }));
